GuessMyDrawing: Thread Class Reference
Thread Class Reference
#include <thread.h>
Public Slots
void onMessageReadyRead ()
void onDisconnectedMessage ()
Signals
void error (QTcpSocket::SocketError socket_error)
void messageReceived (QJsonObject message, Thread *thread)
void finished ()
Public Member Functions
Thread (qintptr ID, QObject *parent=0)
~Thread ()
quintptr getSocketDescriptor ()
void send (QJsonObject message)
void setRoomName (QString room_name)
QString getRoomName ()
void disconnect ()
Detailed Description
Definition at line 11 of file thread.h.
Constructor & Destructor Documentation
Thread()
Thread::Thread (qintptr ID, QObject * parent = 0) explicit
Definition at line 5 of file thread.cpp.
References onDisconnectedMessage(), and onMessageReadyRead().
~Thread()
Thread::~Thread ()
Definition at line 24 of file thread.cpp.
Member Function Documentation
disconnect()
void Thread::disconnect ()
Definition at line 20 of file thread.cpp.
error
void Thread::error (QTcpSocket::SocketError socket_error) signal
Definition at line 181 of file moc_thread.cpp.
finished
void Thread::finished () signal
Definition at line 195 of file moc_thread.cpp.
getRoomName()
QString Thread::getRoomName ()
Definition at line 54 of file thread.cpp.
getSocketDescriptor()
quintptr Thread::getSocketDescriptor ()
Definition at line 46 of file thread.cpp.
messageReceived
void Thread::messageReceived (QJsonObject message, Thread * thread) signal
Definition at line 188 of file moc_thread.cpp.
Referenced by onMessageReadyRead().
onDisconnectedMessage
void Thread::onDisconnectedMessage () slot
Definition at line 41 of file thread.cpp.
Referenced by Thread().
onMessageReadyRead
void Thread::onMessageReadyRead () slot
Definition at line 35 of file thread.cpp.
References messageReceived().
Referenced by Thread().
send()
void Thread::send (QJsonObject message)
Definition at line 28 of file thread.cpp.
Referenced by Room::checkChatWord(), Room::joinClient(), and Server::parseMessage().
setRoomName()
void Thread::setRoomName (QString room_name)
Definition at line 50 of file thread.cpp.
The documentation for this class was generated from the following files:
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Server/thread.h
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/build/Server/moc_thread.cpp
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Server/thread.cpp