GuessMyDrawing: MessageParser Class Reference
MessageParser Class Reference
#include <messageparser.h>
Public Member Functions
MessageParser ()
QJsonObject textMessage (const QString &text, const QString &name)
QJsonObject joinRoomMessage (QString &username, QString &roomName)
QJsonObject createRoomMessage (QString &username, QString &room_name, int duration)
QJsonObject leaveRoomMessage ()
QJsonObject chooseWordMessage (QString &word)
QJsonObject getRoomsMessage ()
QJsonObject canvasMessage (QString &canvas)
MessageReceivedType parseReceivedMessage (const QJsonObject &message, QVector< QString > &ret)
Detailed Description
Definition at line 10 of file messageparser.h.
Constructor & Destructor Documentation
MessageParser()
MessageParser::MessageParser ()
Definition at line 4 of file messageparser.cpp.
Member Function Documentation
canvasMessage()
QJsonObject MessageParser::canvasMessage (QString & canvas)
Definition at line 61 of file messageparser.cpp.
References MessageType::CANVAS_MESSAGE, MessageType::CONTENT, and MessageType::TYPE.
Referenced by Client::sendCanvas().
chooseWordMessage()
QJsonObject MessageParser::chooseWordMessage (QString & word)
Definition at line 46 of file messageparser.cpp.
References MessageType::CHOOSE_WORD, MessageType::CONTENT, and MessageType::TYPE.
Referenced by Client::chooseWord().
createRoomMessage()
QJsonObject MessageParser::createRoomMessage (QString & username, QString & room_name, int duration)
Definition at line 29 of file messageparser.cpp.
References MessageType::CREATE_ROOM, MessageType::DURATION, MessageType::ROOM_NAME, MessageType::TYPE, and MessageType::USERNAME.
Referenced by Client::createRoom().
getRoomsMessage()
QJsonObject MessageParser::getRoomsMessage ()
Definition at line 54 of file messageparser.cpp.
References MessageType::GET_ROOMS, and MessageType::TYPE.
Referenced by Client::getRooms().
joinRoomMessage()
QJsonObject MessageParser::joinRoomMessage (QString & username, QString & roomName)
Definition at line 20 of file messageparser.cpp.
References MessageType::JOIN_ROOM, MessageType::ROOM_NAME, MessageType::TYPE, and MessageType::USERNAME.
Referenced by Client::joinRoom().
leaveRoomMessage()
QJsonObject MessageParser::leaveRoomMessage ()
Definition at line 39 of file messageparser.cpp.
References MessageType::LEAVE_ROOM, and MessageType::TYPE.
Referenced by Client::leaveRoom().
parseReceivedMessage()
MessageReceivedType MessageParser::parseReceivedMessage (const QJsonObject & message, QVector< QString > & ret)
Definition at line 70 of file messageparser.cpp.
References CANVAS_MESSAGE, MessageType::CANVAS_MESSAGE, MessageType::CONTENT, ERROR, GAME_OVER, MessageType::GAME_OVER, GAME_START, GET_ROOMS, MessageType::GET_ROOMS, MessageType::JOIN_ROOM, JOINED_ROOM, MessageType::MESSAGE_SENDER, NEW_HOST, MessageType::NEW_HOST, MessageType::ROOM_NAME, MessageType::START, TEXT_MESSAGE, MessageType::TEXT_MESSAGE, MessageType::TYPE, USER_JOINED, MessageType::USER_JOINED, USER_LEFT, MessageType::USER_LEFT, and MessageType::USERNAME.
textMessage()
QJsonObject MessageParser::textMessage (const QString & text, const QString & name)
Definition at line 9 of file messageparser.cpp.
References MessageType::CONTENT, MessageType::MESSAGE_SENDER, MessageType::TEXT_MESSAGE, and MessageType::TYPE.
Referenced by Client::send().
The documentation for this class was generated from the following files:
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Application/messageparser.h
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Application/messageparser.cpp