GuessMyDrawing: ServerMessageParser Class Reference
ServerMessageParser Class Reference
#include <servermessageparser.h>
Public Member Functions
ServerMessageParser ()
QJsonObject toStartMessage ()
QJsonObject toUserJoinedMessage (QString &username)
QJsonObject toJoinRoomMessage (QString &roomName)
QJsonObject toGameOverMessage ()
QJsonObject toNewHostMessage ()
QJsonObject toUserLeftMessage (QString username)
ServerMessageType getTypeFromMessage (const QJsonObject &message)
QJsonObject toGetRoomsMessage (const QString &rooms)
QVector< QString > fromJoinRoomMessage (const QJsonObject &message)
QVector< QString > fromChooseWordMessage (const QJsonObject &message)
QVector< QString > fromCreateRoomMessage (const QJsonObject &message)
Detailed Description
Definition at line 10 of file servermessageparser.h.
Constructor & Destructor Documentation
ServerMessageParser()
ServerMessageParser::ServerMessageParser ()
Definition at line 4 of file servermessageparser.cpp.
Member Function Documentation
fromChooseWordMessage()
QVector< QString > ServerMessageParser::fromChooseWordMessage (const QJsonObject & message)
Definition at line 108 of file servermessageparser.cpp.
References MessageType::CONTENT.
Referenced by Server::parseMessage().
fromCreateRoomMessage()
QVector< QString > ServerMessageParser::fromCreateRoomMessage (const QJsonObject & message)
Definition at line 115 of file servermessageparser.cpp.
References MessageType::DURATION, MessageType::ROOM_NAME, and MessageType::USERNAME.
Referenced by Server::parseMessage().
fromJoinRoomMessage()
QVector< QString > ServerMessageParser::fromJoinRoomMessage (const QJsonObject & message)
Definition at line 99 of file servermessageparser.cpp.
References MessageType::ROOM_NAME, and MessageType::USERNAME.
Referenced by Server::parseMessage().
getTypeFromMessage()
ServerMessageType ServerMessageParser::getTypeFromMessage (const QJsonObject & message)
Definition at line 67 of file servermessageparser.cpp.
References MessageType::CANVAS_MESSAGE, CANVAS_MESSAGE, MessageType::CHOOSE_WORD, CHOOSE_WORD, MessageType::CREATE_ROOM, CREATE_ROOM, ERROR, MessageType::GET_ROOMS, GET_ROOMS, MessageType::JOIN_ROOM, JOIN_ROOM, MessageType::LEAVE_ROOM, LEAVE_ROOM, MessageType::TEXT_MESSAGE, TEXT_MESSAGE, and MessageType::TYPE.
Referenced by Server::parseMessage().
toGameOverMessage()
QJsonObject ServerMessageParser::toGameOverMessage ()
Definition at line 35 of file servermessageparser.cpp.
References MessageType::GAME_OVER, and MessageType::TYPE.
toGetRoomsMessage()
QJsonObject ServerMessageParser::toGetRoomsMessage (const QString & rooms)
Definition at line 60 of file servermessageparser.cpp.
References MessageType::CONTENT, MessageType::GET_ROOMS, and MessageType::TYPE.
Referenced by Server::parseMessage().
toJoinRoomMessage()
QJsonObject ServerMessageParser::toJoinRoomMessage (QString & roomName)
Definition at line 26 of file servermessageparser.cpp.
References MessageType::JOIN_ROOM, MessageType::ROOM_NAME, and MessageType::TYPE.
Referenced by Room::joinClient().
toNewHostMessage()
QJsonObject ServerMessageParser::toNewHostMessage ()
Definition at line 43 of file servermessageparser.cpp.
References MessageType::NEW_HOST, and MessageType::TYPE.
Referenced by Room::checkChatWord(), Room::joinClient(), and Room::leaveRoom().
toStartMessage()
QJsonObject ServerMessageParser::toStartMessage ()
Definition at line 9 of file servermessageparser.cpp.
References MessageType::START, and MessageType::TYPE.
Referenced by Room::joinClient(), and Room::start().
toUserJoinedMessage()
QJsonObject ServerMessageParser::toUserJoinedMessage (QString & username)
Definition at line 17 of file servermessageparser.cpp.
References MessageType::TYPE, MessageType::USER_JOINED, and MessageType::USERNAME.
Referenced by Room::joinClient().
toUserLeftMessage()
QJsonObject ServerMessageParser::toUserLeftMessage (QString username)
Definition at line 51 of file servermessageparser.cpp.
References MessageType::TYPE, MessageType::USER_LEFT, and MessageType::USERNAME.
Referenced by Room::leaveRoom().
The documentation for this class was generated from the following files:
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Server/servermessageparser.h
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Server/servermessageparser.cpp