GuessMyDrawing: Canvas Class Reference
Canvas Class Reference
#include <canvas.h>
Public Slots
void clearImage ()
Public Member Functions
Canvas (QWidget *parent=nullptr)
~Canvas ()=default
bool isModified () const
QString takeSnapshot ()
void loadFromSnapshot (QString &qstring)
int penWidth () const
void setPenWidth (int width)
void setPenColor (QColor color)
Protected Member Functions
void mousePressEvent (QMouseEvent *event) override
void mouseMoveEvent (QMouseEvent *event) override
void mouseReleaseEvent (QMouseEvent *event) override
void paintEvent (QPaintEvent *event) override
void resizeEvent (QResizeEvent *event) override
Detailed Description
Definition at line 10 of file canvas.h.
Constructor & Destructor Documentation
Canvas()
Canvas::Canvas (QWidget * parent = nullptr)
Definition at line 10 of file canvas.cpp.
~Canvas()
Canvas::~Canvas () default
Member Function Documentation
clearImage
void Canvas::clearImage () slot
Definition at line 52 of file canvas.cpp.
Referenced by Game::onClearDrawing().
isModified()
bool Canvas::isModified () const
Definition at line 16 of file canvas.cpp.
loadFromSnapshot()
void Canvas::loadFromSnapshot (QString & qstring)
Definition at line 30 of file canvas.cpp.
References CanvasSerializer::toQByteArray().
Referenced by Game::onLoadCanvas().
mouseMoveEvent()
void Canvas::mouseMoveEvent (QMouseEvent * event) override protected
Definition at line 67 of file canvas.cpp.
mousePressEvent()
void Canvas::mousePressEvent (QMouseEvent * event) override protected
Definition at line 59 of file canvas.cpp.
mouseReleaseEvent()
void Canvas::mouseReleaseEvent (QMouseEvent * event) override protected
Definition at line 73 of file canvas.cpp.
paintEvent()
void Canvas::paintEvent (QPaintEvent * event) override protected
Definition at line 83 of file canvas.cpp.
penWidth()
int Canvas::penWidth () const
Definition at line 131 of file canvas.cpp.
Referenced by Game::onDecPenWidth(), and Game::onIncPenWidth().
resizeEvent()
void Canvas::resizeEvent (QResizeEvent * event) override protected
Definition at line 92 of file canvas.cpp.
setPenColor()
void Canvas::setPenColor (QColor color)
Definition at line 148 of file canvas.cpp.
Referenced by Game::onChangePenColor().
setPenWidth()
void Canvas::setPenWidth (int width)
Definition at line 135 of file canvas.cpp.
Referenced by Game::onDecPenWidth(), and Game::onIncPenWidth().
takeSnapshot()
QString Canvas::takeSnapshot ()
Definition at line 20 of file canvas.cpp.
References CanvasSerializer::toQString().
The documentation for this class was generated from the following files:
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Application/canvas.h
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Application/canvas.cpp