GuessMyDrawing: Server Class Reference
Server Class Reference
#include <server.h>
Public Slots
void parseMessage (const QJsonObject &message, Thread *thread)
Public Member Functions
Server (QObject *parent=0)
~Server ()
void startServer ()
Protected Member Functions
void incomingConnection (qintptr socketDescriptor)
Detailed Description
Definition at line 13 of file server.h.
Constructor & Destructor Documentation
Server()
Server::Server (QObject * parent = 0) explicit
Definition at line 4 of file server.cpp.
~Server()
Server::~Server ()
Definition at line 173 of file server.cpp.
Member Function Documentation
incomingConnection()
void Server::incomingConnection (qintptr socketDescriptor) protected
Definition at line 16 of file server.cpp.
References parseMessage().
parseMessage
void Server::parseMessage (const QJsonObject & message, Thread * thread) slot
Definition at line 25 of file server.cpp.
References CANVAS_MESSAGE, CHOOSE_WORD, CREATE_ROOM, ERROR, ServerMessageParser::fromChooseWordMessage(), ServerMessageParser::fromCreateRoomMessage(), ServerMessageParser::fromJoinRoomMessage(), GET_ROOMS, ServerMessageParser::getTypeFromMessage(), JOIN_ROOM, LEAVE_ROOM, Thread::send(), TEXT_MESSAGE, and ServerMessageParser::toGetRoomsMessage().
Referenced by incomingConnection().
startServer()
void Server::startServer ()
Definition at line 8 of file server.cpp.
Referenced by main().
The documentation for this class was generated from the following files:
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Server/server.h
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Server/server.cpp