GuessMyDrawing: Client Class Reference
Client Class Reference
#include <client.h>
Signals
void messageReceived (const QString &sender, const QString &test)
void userJoined (const QString &username)
void userLeft (const QString &username)
void roomList (const QVector< QString > *rooms)
void joinedRoom (bool &success)
void youAreNewHost ()
void errorConnecting ()
void startGame ()
void gameOver ()
void canvasReceived (QString data)
Public Member Functions
Client (QString name, QObject *parent=nullptr)
~Client ()
void connectToServer (const QHostAddress &adress, quint16 port)
void disconnectFromHost ()
void send (const QString &text)
void joinRoom (QString username, QString room)
void createRoom (QString username, QString room_name, int duration)
void leaveRoom ()
void chooseWord (QString word)
void getRooms ()
void sendCanvas (QString &canvas)
bool isHost ()
void reconnect ()
Detailed Description
Definition at line 19 of file client.h.
Constructor & Destructor Documentation
Client()
Client::Client (QString name, QObject * parent = nullptr) explicit
Definition at line 5 of file client.cpp.
~Client()
Client::~Client ()
Definition at line 23 of file client.cpp.
Member Function Documentation
canvasReceived
void Client::canvasReceived (QString data) signal
Definition at line 335 of file moc_client.cpp.
Referenced by Game::Game().
chooseWord()
void Client::chooseWord (QString word)
Definition at line 66 of file client.cpp.
References MessageParser::chooseWordMessage().
connectToServer()
void Client::connectToServer (const QHostAddress & adress, quint16 port)
Definition at line 29 of file client.cpp.
Referenced by MainWindow::attemptConnection(), and reconnect().
createRoom()
void Client::createRoom (QString username, QString room_name, int duration)
Definition at line 52 of file client.cpp.
References MessageParser::createRoomMessage().
Referenced by Settings::sendSettingsToCLient().
disconnectFromHost()
void Client::disconnectFromHost ()
Definition at line 36 of file client.cpp.
errorConnecting
void Client::errorConnecting () signal
Definition at line 317 of file moc_client.cpp.
Referenced by ChooseWord::ChooseWord(), ExistingRooms::ExistingRooms(), Game::Game(), MainWindow::MainWindow(), and Settings::Settings().
gameOver
void Client::gameOver () signal
Definition at line 329 of file moc_client.cpp.
Referenced by Game::Game().
getRooms()
void Client::getRooms ()
Definition at line 71 of file client.cpp.
References MessageParser::getRoomsMessage().
Referenced by MainWindow::JoinGameClicked().
isHost()
bool Client::isHost () inline
Definition at line 39 of file client.h.
joinedRoom
void Client::joinedRoom (bool & success) signal
Definition at line 304 of file moc_client.cpp.
Referenced by ExistingRooms::ExistingRooms().
joinRoom()
void Client::joinRoom (QString username, QString room)
Definition at line 46 of file client.cpp.
References MessageParser::joinRoomMessage().
leaveRoom()
void Client::leaveRoom ()
Definition at line 58 of file client.cpp.
References MessageParser::leaveRoomMessage().
Referenced by Game::closeEvent().
messageReceived
void Client::messageReceived (const QString & sender, const QString & test) signal
Definition at line 276 of file moc_client.cpp.
Referenced by Game::Game().
reconnect()
void Client::reconnect ()
Definition at line 81 of file client.cpp.
References connectToServer().
roomList
void Client::roomList (const QVector< QString > * rooms) signal
Definition at line 297 of file moc_client.cpp.
Referenced by ExistingRooms::ExistingRooms().
send()
void Client::send (const QString & text)
Definition at line 41 of file client.cpp.
References MessageParser::textMessage().
sendCanvas()
void Client::sendCanvas (QString & canvas)
Definition at line 76 of file client.cpp.
References MessageParser::canvasMessage().
startGame
void Client::startGame () signal
Definition at line 323 of file moc_client.cpp.
Referenced by Game::Game().
userJoined
void Client::userJoined (const QString & username) signal
Definition at line 283 of file moc_client.cpp.
Referenced by Game::Game().
userLeft
void Client::userLeft (const QString & username) signal
Definition at line 290 of file moc_client.cpp.
Referenced by Game::Game().
youAreNewHost
void Client::youAreNewHost () signal
Definition at line 311 of file moc_client.cpp.
Referenced by Game::Game().
The documentation for this class was generated from the following files:
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Application/client.h
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Application/client.cpp
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/build/Application/moc_client.cpp