GuessMyDrawing: Game Class Reference
Game Class Reference
#include <game.h>
Public Slots
void onClearDrawing ()
void onChangePenColor ()
void onIncPenWidth ()
void onDecPenWidth ()
void onLoadCanvas (QString s)
Signals
void IAmHost ()
void LeaveClicked ()
Public Member Functions
Game (Client *client, QWidget *parent=nullptr)
~Game ()
Canvas * getCanvas () const
int getDuration () const
void setDuration (int newDuration)
void closeEvent (QCloseEvent *event) override
Detailed Description
Definition at line 17 of file game.h.
Constructor & Destructor Documentation
Game()
Game::Game (Client * client, QWidget * parent = nullptr) explicit
Definition at line 8 of file game.cpp.
References Ui_Game::btnSend, Client::canvasReceived(), Ui_Game::cbPenColor, Client::errorConnecting(), Client::gameOver(), Ui_Game::leInput, Ui_Game::listView, Client::messageReceived(), onChangePenColor(), onClearDrawing(), onDecPenWidth(), onIncPenWidth(), onLoadCanvas(), Ui_Game::pbClearDrawing, Ui_Game::pbDecPenWidth, Ui_Game::pbIncPenWidth, Ui_Game::setupUi(), Client::startGame(), Client::userJoined(), Client::userLeft(), and Client::youAreNewHost().
~Game()
Game::~Game ()
Definition at line 56 of file game.cpp.
Member Function Documentation
closeEvent()
void Game::closeEvent (QCloseEvent * event) override
Definition at line 132 of file game.cpp.
References Client::leaveRoom().
getCanvas()
Canvas * Game::getCanvas () const
Definition at line 64 of file game.cpp.
getDuration()
int Game::getDuration () const
Definition at line 121 of file game.cpp.
IAmHost
void Game::IAmHost () signal
Definition at line 209 of file moc_game.cpp.
Referenced by ChooseWord::ChooseWord().
LeaveClicked
void Game::LeaveClicked () signal
Definition at line 215 of file moc_game.cpp.
onChangePenColor
void Game::onChangePenColor () slot
Definition at line 74 of file game.cpp.
References Ui_Game::cbPenColor, and Canvas::setPenColor().
Referenced by Game().
onClearDrawing
void Game::onClearDrawing () slot
Definition at line 69 of file game.cpp.
References Canvas::clearImage().
Referenced by Game().
onDecPenWidth
void Game::onDecPenWidth () slot
Definition at line 104 of file game.cpp.
References Canvas::penWidth(), and Canvas::setPenWidth().
Referenced by Game().
onIncPenWidth
void Game::onIncPenWidth () slot
Definition at line 98 of file game.cpp.
References Canvas::penWidth(), and Canvas::setPenWidth().
Referenced by Game().
onLoadCanvas
void Game::onLoadCanvas (QString s) slot
Definition at line 110 of file game.cpp.
References Canvas::loadFromSnapshot().
Referenced by Game().
setDuration()
void Game::setDuration (int newDuration)
Definition at line 126 of file game.cpp.
The documentation for this class was generated from the following files:
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Application/game.h
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Application/game.cpp
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/build/Application/moc_game.cpp