GuessMyDrawing: Settings Class Reference
Settings Class Reference
#include <settings.h>
Signals
void signalThatGameWindowIsClosed ()
Public Member Functions
Settings (Game *game, Client *client, QWidget *parent=nullptr)
~Settings ()
void sendSettingsToCLient (QString username, QString roomName, int duration)
void disableInputs ()
Detailed Description
Definition at line 14 of file settings.h.
Constructor & Destructor Documentation
Settings()
Settings::Settings (Game * game, Client * client, QWidget * parent = nullptr) explicit
Definition at line 7 of file settings.cpp.
References disableInputs(), Client::errorConnecting(), Ui_Settings::leUsername, Ui_Settings::lnRoomName, Ui_Settings::pbSave, Ui_Settings::pushButton_2, Ui_Settings::rBtn120, Ui_Settings::rBtn60, Ui_Settings::rBtn90, and Ui_Settings::setupUi().
~Settings()
Settings::~Settings ()
Definition at line 29 of file settings.cpp.
Member Function Documentation
disableInputs()
void Settings::disableInputs ()
Definition at line 107 of file settings.cpp.
References Ui_Settings::leUsername, Ui_Settings::lnRoomName, Ui_Settings::pbSave, Ui_Settings::rBtn120, Ui_Settings::rBtn60, and Ui_Settings::rBtn90.
Referenced by MainWindow::CreateNewGameClicked(), and Settings().
sendSettingsToCLient()
void Settings::sendSettingsToCLient (QString username, QString roomName, int duration)
Definition at line 77 of file settings.cpp.
References Client::createRoom().
signalThatGameWindowIsClosed
void Settings::signalThatGameWindowIsClosed () signal
Definition at line 170 of file moc_settings.cpp.
The documentation for this class was generated from the following files:
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Application/settings.h
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Application/settings.cpp
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/build/Application/moc_settings.cpp