GuessMyDrawing: ExistingRooms Class Reference
ExistingRooms Class Reference
#include <existingrooms.h>
Public Member Functions
ExistingRooms (Game *game, Client *client, QWidget *parent=nullptr)
~ExistingRooms ()
Detailed Description
Definition at line 14 of file existingrooms.h.
Constructor & Destructor Documentation
ExistingRooms()
ExistingRooms::ExistingRooms (Game * game, Client * client, QWidget * parent = nullptr) explicit
Definition at line 5 of file existingrooms.cpp.
References Client::errorConnecting(), Client::joinedRoom(), Ui_ExistingRooms::leUsername, Ui_ExistingRooms::listOfRooms, Ui_ExistingRooms::pbJoin, Client::roomList(), and Ui_ExistingRooms::setupUi().
~ExistingRooms()
ExistingRooms::~ExistingRooms ()
Definition at line 26 of file existingrooms.cpp.
The documentation for this class was generated from the following files:
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Application/existingrooms.h
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Application/existingrooms.cpp