GuessMyDrawing: ChooseWord Class Reference
ChooseWord Class Reference
#include <chooseword.h>
Public Member Functions
ChooseWord (Game *game, Client *client, QWidget *parent=nullptr)
~ChooseWord ()
Detailed Description
Definition at line 12 of file chooseword.h.
Constructor & Destructor Documentation
ChooseWord()
ChooseWord::ChooseWord (Game * game, Client * client, QWidget * parent = nullptr) explicit
Definition at line 6 of file chooseword.cpp.
References Client::errorConnecting(), Game::IAmHost(), Ui_ChooseWord::lnInsertWord, Ui_ChooseWord::pbCreateGame, Ui_ChooseWord::pbFirstWord, Ui_ChooseWord::pbSecondWord, Ui_ChooseWord::pbThirdWord, Ui_ChooseWord::pbUseMyWord, and Ui_ChooseWord::setupUi().
~ChooseWord()
ChooseWord::~ChooseWord ()
Definition at line 31 of file chooseword.cpp.
The documentation for this class was generated from the following files:
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Application/chooseword.h
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Application/chooseword.cpp