GuessMyDrawing: Room Class Reference
Room Class Reference
#include <room.h>
Public Member Functions
Room (QString firstHost, QString roomName, int duration)
~Room ()
void broadcastMessage (const QJsonObject &message, Thread *t)
void broadcastCanvas (const QJsonObject &message, Thread *t)
void start ()
void setDuration (int newDuration)
void leaveRoom (Thread *thread)
bool usernameIsTaken (QString username)
void setWordAndStartGame (const QString &newChosenWord)
void checkChatWord (QString word, Thread *senderUser)
void joinClient (QString username, Thread *thread)
QString getWord ()
Detailed Description
Definition at line 14 of file room.h.
Constructor & Destructor Documentation
Room()
Room::Room (QString firstHost, QString roomName, int duration)
Definition at line 7 of file room.cpp.
~Room()
Room::~Room ()
Definition at line 13 of file room.cpp.
Member Function Documentation
broadcastCanvas()
void Room::broadcastCanvas (const QJsonObject & message, Thread * t)
Definition at line 199 of file room.cpp.
broadcastMessage()
void Room::broadcastMessage (const QJsonObject & message, Thread * t)
Definition at line 186 of file room.cpp.
References checkChatWord(), MessageType::CONTENT, MessageType::TEXT_MESSAGE, and MessageType::TYPE.
Referenced by joinClient(), and leaveRoom().
checkChatWord()
void Room::checkChatWord (QString word, Thread * senderUser)
Definition at line 79 of file room.cpp.
References Thread::send(), and ServerMessageParser::toNewHostMessage().
Referenced by broadcastMessage().
getWord()
QString Room::getWord () inline
Definition at line 48 of file room.h.
joinClient()
void Room::joinClient (QString username, Thread * thread)
Definition at line 126 of file room.cpp.
References broadcastMessage(), Thread::send(), start(), ServerMessageParser::toJoinRoomMessage(), ServerMessageParser::toNewHostMessage(), ServerMessageParser::toStartMessage(), ServerMessageParser::toUserJoinedMessage(), and usernameIsTaken().
leaveRoom()
void Room::leaveRoom (Thread * thread)
Definition at line 25 of file room.cpp.
References broadcastMessage(), ServerMessageParser::toNewHostMessage(), and ServerMessageParser::toUserLeftMessage().
setDuration()
void Room::setDuration (int newDuration)
Definition at line 20 of file room.cpp.
setWordAndStartGame()
void Room::setWordAndStartGame (const QString & newChosenWord)
Definition at line 71 of file room.cpp.
References start().
start()
void Room::start ()
Definition at line 172 of file room.cpp.
References ServerMessageParser::toStartMessage().
Referenced by joinClient(), and setWordAndStartGame().
usernameIsTaken()
bool Room::usernameIsTaken (QString username)
Definition at line 62 of file room.cpp.
Referenced by joinClient().
The documentation for this class was generated from the following files:
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Server/room.h
/home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/Server/room.cpp