GuessMyDrawing: /home/jelena/Desktop/faks/vs/07-GuessMyDrawing-master/07-GuessMyDrawing/build/Application/qrc_background.cpp File Reference
qrc_background.cpp File Reference
Macros
#define QT_RCC_PREPEND_NAMESPACE(name) name
#define QT_RCC_MANGLE_NAMESPACE(name) name
Functions
bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
int QT_RCC_MANGLE_NAMESPACE() qInitResources_background ()
int QT_RCC_MANGLE_NAMESPACE() qCleanupResources_background ()
Variables
static const unsigned char qt_resource_data []
static const unsigned char qt_resource_name []
static const unsigned char qt_resource_struct []
Macro Definition Documentation
QT_RCC_MANGLE_NAMESPACE
#define QT_RCC_MANGLE_NAMESPACE (name) name
Definition at line 12524 of file qrc_background.cpp.
QT_RCC_PREPEND_NAMESPACE
#define QT_RCC_PREPEND_NAMESPACE (name) name
Definition at line 12523 of file qrc_background.cpp.
Function Documentation
qCleanupResources_background()
int QT_RCC_MANGLE_NAMESPACE() qCleanupResources_background ()
Definition at line 12548 of file qrc_background.cpp.
References QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, qt_resource_struct, and qUnregisterResourceData().
qInitResources_background()
int QT_RCC_MANGLE_NAMESPACE() qInitResources_background ()
Definition at line 12539 of file qrc_background.cpp.
References qRegisterResourceData(), QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, and qt_resource_struct.
qRegisterResourceData()
bool qRegisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qInitResources_background().
qUnregisterResourceData()
bool qUnregisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qCleanupResources_background().
Variable Documentation
qt_resource_data
const unsigned char qt_resource_data[] static
Definition at line 9 of file qrc_background.cpp.
Referenced by qCleanupResources_background(), and qInitResources_background().
qt_resource_name
const unsigned char qt_resource_name[] static
Initial value:
= {
  0x0,0x3,
  0x0,0x0,0x70,0x37,
  0x0,0x69,
  0x0,0x6d,0x0,0x67,
  0x0,0xe,
  0x7,0x4,0x99,0xa7,
  0x0,0x62,
  0x0,0x61,0x0,0x63,0x0,0x6b,0x0,0x67,0x0,0x72,0x0,0x6f,0x0,0x75,0x0,0x6e,0x0,0x64,0x0,0x2e,0x0,0x6a,0x0,0x70,0x0,0x67,
}
Definition at line 12488 of file qrc_background.cpp.
Referenced by qCleanupResources_background(), and qInitResources_background().
qt_resource_struct
const unsigned char qt_resource_struct[] static
Initial value:
= {
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x1,
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x2,
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,
  0x0,0x0,0x0,0xc,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,
0x0,0x0,0x1,0x7e,0x11,0xb8,0x39,0x28,
}
Definition at line 12502 of file qrc_background.cpp.
Referenced by qCleanupResources_background(), and qInitResources_background().